### ISSUE TITLE
Compile error on gcc 5.3.0

### ISSUE THREAD

**Issue by houzi-** [dirkvdb/ps3netsrv--#12]
```
root@HOUZI:/mmc/compile/ps3netsrv--# make CXX=g++
g++ -c -O3 -I./utils/inc -D_FILE_OFFSET_BITS=64 -DCONSOLE_SUPPORTS_COLOR -Wall -std=c++11 -Wfatal-errors ps3netsrv.cpp -o ps3netsrv.o
ps3netsrv.cpp: In function 'int main(int, char**)':
ps3netsrv.cpp:648:20: error: 'stoi' is not a member of 'std'
             port = std::stoi(optarg);
                    ^
compilation terminated due to -Wfatal-errors.
Makefile:16: recipe for target 'ps3netsrv.o' failed
make: *** [ps3netsrv.o] Error 1
```

**Comment by Pandoriaantje** [comment]
Distro related maybe?
as it compiles just fine with g++ on Arch Linux.

> 
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /build/gcc-multilib/src/gcc-5-20160209/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 5.3.0 (GCC)

**Comment by dirkvdb** [comment]
I added a string include, maybe it helps for your gcc version

**Comment by houzi-** [comment]
thanks

**Comment by houzi-** [comment]
thanks

**Comment by houzi-** [comment]
i try to compile
