### ISSUE TITLE
can't compile under OS X 10.10

### ISSUE THREAD

**Issue by ale275** [dirkvdb/ps3netsrv--#9]
I've opened the Xcode project but can't compile it, the same from terminal.

make
clang++ -c -O3 -I./utils/inc -D_FILE_OFFSET_BITS=64 -DCONSOLE_SUPPORTS_COLOR -Wall -std=c++11 -Wfatal-errors -stdlib=libc++ ps3netsrv.cpp -o ps3netsrv.o
ps3netsrv.cpp:30:10: fatal error: expected ')'
uint64_t htonll(uint64_t val)
         ^
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
ps3netsrv.cpp:30:10: note: to match this '('
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
1 error generated.
make: *** [ps3netsrv.o] Error 1

both with g++ and clang

**Comment by dirkvdb** [comment]
I delivered a fix for osx compilation
